# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowlage01', '0004_auto_20170717_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(max_length=64, verbose_name='博客主题'),
        ),
    ]
