# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowlage01', '0005_auto_20170718_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.ImageField(upload_to='static/img', verbose_name='头像'),
        ),
    ]
