# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowlage01', '0006_auto_20170720_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='dowm_count',
            field=models.IntegerField(default=0, null=True, verbose_name='点踩数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_count',
            field=models.IntegerField(default=0, null=True, verbose_name='点赞数'),
        ),
    ]
